package ru.todo.model;

public enum TaskStatus {
    /*
    CREATED,
    WAITINGFORACTIVATION,
    WAITINGTORUN,
    RUNNING,
    WAITINGFORCHILDRENTOCOMPLETE,
    RANTOCOMPLETION,
    CANCELED,
    FAULTED;
    */
    CREATED,
    ACTIVE,
    PAUSED,
    CANCELED,
    COMPLETED;
}
